# Generated by Django 4.2 on 2025-03-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='test',
            field=models.CharField(default='test test', max_length=10),
            preserve_default=False,
        ),
    ]
