# Generated by Django 4.2 on 2025-03-02 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_movie_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='test',
        ),
    ]
